services:
  kripticc_cockroach:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data
